export const TERM_CHAR = "\u0000", // terminal character
  TERM_CODE = 0, // terminal character code
  ROOT_ID = 0, // index of root node
  NOT_FOUND = -1, // traverse() returns if no nodes found
  BASE_SIGNED = true,
  CHECK_SIGNED = true,
  BASE_BYTES = 4,
  CHECK_BYTES = 4,
  MEMORY_EXPAND_RATIO = 2;
